sudo: required

language: generic

services:
  - docker

before_install:
  - docker --version
  - docker-compose --version

script:
  - docker-compose build
  - docker-compose run cpu python -m doctest fizbuzz.py